# general redirection
[[redirects]]
from = "/r/*"
to = "https://capi.phil.us/api/redirect/:splat"
status = 302


# phil-enroll redirection
[[redirects]]
from = "/e/*"
to = "https://enroll.phil.us/landing/:splat"
status = 302

[[redirects]]
from = "/stage/e/*"
to = "https://enroll.stage.phil.us/landing/:splat"
status = 302

[[redirects]]
from = "/dev/e/*"
to = "https://enroll.dev.phil.us/landing/:splat"
status = 302

# faqs redirection
[[redirects]]
from = "/faqs/*"
to = "/resources/#faqs"
status = 200

[[redirects]]
from = "/about-us/*"
to = "/company"
status = 200

[[redirects]]
from = "/manufacturers/*"
to = "/life-sciences"
status = 301

[[redirects]]
from = "/newpatient/*"
to = "/patients"
status = 200

[[redirects]]
from = "/company/"
to = "/company"
status = 301

[[redirects]]
from = "/life-sciences/"
to = "/life-sciences"
status = 301

[[redirects]]
from = "/patients/"
to = "/patients"
status = 301

[[redirects]]
from = "/healthcare-providers/"
to = "/healthcare-providers"
status = 301

[[redirects]]
from = "/newprovider/*"
to = "/healthcare-providers"
status = 200

[[redirects]]
from = "/pharmacists/*"
to = "/healthcare-providers"
status = 200

[[redirects]]
from = "/connect/*"
to = "/contact"
status = 200

[[redirects]]
from = "/press-releases"
to = "/resources"
status = 200

# redirect blog.phil.us to phil.us as 301 Moved Permanently
[[redirects]]
from = "http://blog.phil.us/*"
to = "http://phil.us/:splat"
status = 301
force = true

[[redirects]]
from = "https://blog.phil.us/*"
to = "https://phil.us/:splat"
status = 301
force = true


# Production context: all deploys from the Production branch
# set in your site’s Branches settings in the UI will inherit
# these settings. You can define environment variables
# here but we recommend using the Netlify UI for sensitive
# values to keep them out of your source repository.
[context.production]
  CONTENTFUL_ENVIRONMENT = "master"

# Here is an example of how to define context-specific
# environment variables. Be mindful when using this
# option and avoid committing sensitive values to public
# source repositories.
[context.deploy-preview.environment]
  NODE_ENV = "development"
  
# Branch Deploy context: all deploys that are not from
# a pull/merge request or from the Production branch
# will inherit these settings.
[context.branch-deploy.environment]
  NODE_ENV = "development"

# Dev context: environment variables set here 
# are available for local development environments 
# run using Netlify Dev. These values can be 
# overwritten on branches that have a more specific 
# branch context configured.
[context.develop.environment]
  NODE_ENV = "development"
  CONTENTFUL_ENVIRONMENT = "develop"

# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.stage.environment] # “staging” is a branch name
  NODE_ENV = "development"
  CONTENTFUL_ENVIRONMENT = "stage"
