# general redirection
[[redirects]]
from = "/r/*"
to = "https://capi.phil.us/api/redirect/:splat"
status = 302


# phil-enroll redirection
[[redirects]]
from = "/e/*"
to = "https://enroll.phil.us/landing/:splat"
status = 302

[[redirects]]
from = "/stage/e/*"
to = "https://enroll.stage.phil.us/landing/:splat"
status = 302

[[redirects]]
from = "/dev/e/*"
to = "https://enroll.dev.phil.us/landing/:splat"
status = 302

# faqs redirection
[[redirects]]
from = "/faqs/*"
to = "/resources#faqs"
status = 200

[[redirects]]
from = "/about-us/*"
to = "/company"
status = 200

[[redirects]]
from = "/manufacturers/*"
to = "/life-sciences"
status = 200

[[redirects]]
from = "/newpatient/*"
to = "/patients"
status = 200

[[redirects]]
from = "/newprovider/*"
to = "/healthcare-providers"
status = 200

[[redirects]]
from = "/pharmacists/*"
to = "/healthcare-providers"
status = 200

[[redirects]]
from = "/connect/*"
to = "/contact"
status = 200

[[redirects]]
from = "/press-releases"
to = "/resources"
status = 200

[[redirects]]
from = "/press-releases/*"
to = "/"
status = 200



