export const TRAINNING_DATA = `
    You are an AI assistant for the PHIL team. Your persona is friendly, professional, and knowledgeable.
    Your knowledge is strictly limited to the following content. Use this information to answer user questions.
    If a user asks a question that cannot be answered by the provided content, you MUST respond with the exact phrase "INSUFFICIENT_INFO".
    Do not provide any other information or attempt to answer questions outside of this knowledge base.
    
    # KNOWLEDGE BASE

    **Key Products & Services:**

    **Use Cases:**

    **Contact Information:**
    For more information, please visit www.phil.us/demo.

    Pharma Direct-to-Patient: From Experiment to Imperative
    Policy pressure, affordability gaps, and consumer expectations are reshaping how pharma companies think about direct to patient access. The question is no longer if, but how.
    Authors: Deepak Thomas, Fred Hassan, and Sari Kaganoff
    New Pathways for Patient Access
    Pharmaceutical companies are under pressure to rethink how patients get medicines. Costs have piled up across the channel, including PBM spread, rebates, and distribution fees. For patients, the impact is obvious: prior authorization and benefit design often block therapy even when coverage exists. 
    At the same time, patients are behaving more like consumers. They expect digital access, transparent pricing, and streamlined service. According to a report by McKinsey, “Consumers are more motivated than ever to choose healthcare options that offer a better experience, higher quality of care, and greater value.” The mismatch between expectations and the reality of the drug channel has created pressure from both sides.
    While early examples of pharma companies offering direct-to-patient (DTP) access channels have existed for several years, recently, several leading pharma companies, including Eli Lilly, Pfizer, and Novo Nordisk, have made headlines for launching direct-to-patient programs to reduce some of this friction. Early impact is visible with reports that over one third of US Zepbound prescriptions now run through LillyDirect. Roche’s CEO has recently said the company is exploring selling drugs directly to U.S. consumers “which would cut out pharmacy benefit managers”
    Recent actions by the administration are accelerating the shift. In late July, President Trump sent letters to 17 drugmakers demanding they Participate in Direct‑to‑Consumer (DTC) channels, offering patients most favored nation pricing on high volume, high rebate drugs, and set a September 29 deadline to commit.
    The pressure is no longer theoretical. Policy deadlines, competitive moves, and consumer expectations are converging. Direct-to-patient access has moved from an interesting experiment to an executive-level priority. The question has shifted from whether to try it to how to execute successfully.
    Getting the Program Design Right
    Building direct-to-patient access is not just about standing up a new channel. Success depends on designing around a few core considerations that determine whether patients actually get on therapy and whether the model is sustainable for the company. A good case study for how this can work is GLP-1 medications (where Lilly and Novo both started.)
    Affordability. Most DTP programs sell the medications to patients for cash at Gross-to-net (GTN) level prices, meaning the price level that they receive after paying rebates and channel costs. However, GTN-level cash prices are out of reach for most patients. GLP-1s sold directly top patients cost $499 a month, which is out of reach for most patients. (Compared to the $25 out of pocket a patient covered by insurance can pay.) At current cash price points, many patients simply walk away. Even among those highly motivated to start therapy, most cannot sustain hundreds of dollars a month out-of-pocket. A study by Rock Health found that 47% of consumers considering GLP-1s cited cost as the top deterrent, and 36% of past users stopped treatment due to cost. Pharma companies need to develop models that expand access while providing options both for insurance and cash.
    Service model design. Direct-to-patient channels can include many different service offerings, including telemedicine, prescription fulfillment, care navigation, and adherence support. Some of these services are offered directly by the pharmaceutical company, but more often than not, they are offered via partners. Determining which components to include in your DTP channel is a key design question, and often depends on the therapeutic area of the medications you are offering. For example, for some treatment areas, like migraine, sexual health, and obesity, offering access to prescribers is important because it can be hard for patients to find providers who are experienced with that treatment area, or they may be uncomfortable discussing the condition with their primary care clinician. Other medications are really more focused on cost of the medication and pharmacy services are the most critical.
    Navigation burden. As we mentioned, today, patients often stitch together prescribing, fulfillment, and support across multiple vendors. Convoluted navigation flows and excessive handoffs increase friction. The burden should not fall on patients to figure out which customer service they need to reach out to, navigate to the correct vendor, or repeatedly enter information into intake forms. Even small points of friction can erode trust; Redpoint Global found that digital friction drops recommendation scores by 13 points.
    Awareness and discovery. As any consumer product would know, launching a channel isn’t sufficient to drive awareness. Patients must know that these programs exist.  A Press Ganey survey found that patients now rely on digital sources 3.1 times more than provider referrals when choosing a provider. Pfizer publicized the launch of PfizerforAll with a superbowl ad, and while not every pharma company will go that route, ensuring that they are building awareness and driving consumers to the channel they are offering is critical.
    Compliance. As with anything in the pharma realm, there are critical regulatory and compliance guidelines to keep in mind when designing a DTP channel. Three of the key issues to keep in mind are patient steerage, physician choice, and patient data privacy. Patient steerage refers to nudging patients toward a channel or payment path for financial reasons. Physician choice concerns improperly influencing prescriber decision-making. Programs must be designed to protect against both while keeping data privacy intact.
    Solution approaches
    For each of the areas we highlighted, there are approaches that will help direct patients to what is needed.
    Affordability. Start with an insurance-first workflow. While some patients may not have coverage, often it’s a matter of making sure the provider is correctly completing prior authorization forms. Offering patients the ability to first use their insurance coverage, and if that fails, cash as an alternative, rather than assuming they default to cash in a direct to patient model. Another option can be to use a bridge model that allows patients to pay cash for the first prescription while insurance is being processed, so treatment is not delayed. Another area of affordability is the doctor visits offered via partnerships. Be transparent about visit costs upfront, and enable one-time visits rather than forcing ongoing subscriptions.
    Service model design. Tailor the service stack to the therapeutic area. For more complex or sensitive conditions, integrate telehealth with specialist networks. For other conditions, cost of medication or complex prior authorization requirements may be the primary barrier, which means focusing on fulfillment and prior auth support may be the primary focus.
    Reduce navigation burden. Create one front door with a seamless transition for patients from one service to another. Single data intake without requiring them to input information more then ones. Ideally enable patients to go through one streamlined process weather they have insurance or not, to make it easier for them to get the lowest cost option, and not require them to know in advance what their benefits status is. Use an orchestration layer that eliminates jarring handoffs and persists patient context across vendors. Provide real-time visibility into the status of a prescription, whether it’s going through prior authorization, fulfillment, shipment, etc. 
    Drive awareness and discovery. Treat your DTP channel like you would a drug product, by marketing and advertising the channel directly, via a variety of mediums and channels. Track the success of different channels for driving awareness and adapt accordingly.
    Design for compliance. Build telemedicine with an external physician group to avoid steerage. Preserve physician making authority by not letting them know which channel the patient came from. Ensure patients authorize their data sharing and protect sensitive data behind firewalls, using unique identifiers to track patient flow through the system. Conduct pre-launch legal review and ongoing monitoring to keep programs aligned with evolving standards.
    Acting on the Opportunity
    Direct-to-patient access is no longer optional, policy pressure now comes with explicit timelines. The administration’s demands are clear, making affordability and access a near-term compliance and legal risk, not a future ideal. Consumers are clear that cost and access remain the biggest barriers.
    What to do now: start with a priority brand and design the experience based on its specific access challenges. Build for compliance from day one. Make it consumer-grade with one front door, real pricing transparency, automated coverage checks, and a seamless journey without handoffs. Default to coverage, then offer cash as a bridge or fallback. 
    The companies that act to set up these channels well, and in a way that achieves the best outcome for patients will set the standard. Those that delay will be reacting to regulators, competitors, and patients who have already moved ahead.
  `;

export enum MSG_SENDER {
  USER = "user",
  AI = "ai",
}