export interface ResourceItem {
  title: string;
  topics: string[];
  type: "report" | "press" | "webinar" | "blog" | "casestudy";
  url: string;
  buttonLabel: string;
}

export const RESOURCES_DATA: ResourceItem[] = [
  {
    title: "Protecting Gross-to-Net Performance Through Single-Channel Ecosystems",
    topics: ["access", "commercial"],
    type: "press",
    url: "https://www.drugchannels.net/2026/05/protecting-gross-to-net-performance.html",
    buttonLabel: "Read",
  },
  {
    title: "Building Direct-to-Patient Programs that Exceed Today's Patient Expectations",
    topics: ["direct", "patient"],
    type: "report",
    url: "https://phil.us/dtp-research/",
    buttonLabel: "Download",
  },
  {
    title: "Tenpoint Therapeutics Ltd and PHIL Partner to Launch YUVEZZI™ Direct-to-Patient Cash Program",
    topics: ["direct", "access"],
    type: "press",
    url: "https://www.businesswire.com/news/home/20260402677480/en/Tenpoint-Therapeutics-Ltd-and-PHIL-Partner-to-Launch-YUVEZZI-Direct-to-Patient-Cash-Program-to-Make-Novel-Presbyopia-Therapy-More-Accessible-and-Affordable",
    buttonLabel: "Read",
  },
  {
    title: "Bridging the Gap to Better Patient Outcomes: What HCPs Want from Pharma's Digital Access Channels",
    topics: ["direct", "field", "data"],
    type: "report",
    url: "https://phil.us/hcp-research/",
    buttonLabel: "Download",
  },
  {
    title: "Capturing Actionable Metrics to Improve Patient & Brand Outcomes",
    topics: ["data", "commercial", "patient"],
    type: "webinar",
    url: "https://phil.us/on-demand-webinar-capturing-actionable-metrics-to-improve-patient-and-brand/",
    buttonLabel: "Watch",
  },
  {
    title: "The Hidden GTN Drain: Why Specialty-Lite Brands Need To Streamline The PA Process",
    topics: ["utilization", "commercial"],
    type: "press",
    url: "https://www.fiercepharma.com/sponsored/hidden-gtn-drain-why-specialty-lite-brands-need-streamline-their-pa-process-optimal",
    buttonLabel: "Read",
  },
  {
    title: "Sprout Pharmaceuticals and PHIL Expand Their Affordable Direct-to-Patient Access Program for Addyi",
    topics: ["direct", "access"],
    type: "press",
    url: "https://www.prnewswire.com/news-releases/phil-and-sprout-pharmaceuticals-expand-their-affordable-direct-to-patient-access-program-for-addyiflibanserin-302655793.html?",
    buttonLabel: "Read",
  },
  {
    title: "Redefining Commercial Success in Speciaty-Lite",
    topics: ["access", "commercial"],
    type: "press",
    url: "https://www.biopharmadive.com/spons/redefining-commercial-success-in-specialty-lite-with-alternative-channels/753650/",
    buttonLabel: "Read",
  },
  {
    title: "Pharma Direct-To-Patient 2.0: From Experiment To Imperative",
    topics: ["direct", "access"],
    type: "press",
    url: "https://www.lifescienceleader.com/doc/pharma-direct-to-patient-from-experiment-to-imperative-0001",
    buttonLabel: "Read",
  },
  {
    title: "PHIL Launches Direct-to-Patient 2.0 Platform to Transform Access, Affordability, and Adherence in Pharma",
    topics: ["direct", "access"],
    type: "press",
    url: "https://www.businesswire.com/news/home/20250922836527/en/PHIL-Launches-Direct-to-Patient-2.0-Platform-to-Transform-Access-Affordability-and-Adherence-in-Pharma",
    buttonLabel: "Read",
  },
  {
    title: "Bridging Data Gaps that Impact Retail and Specialty-Lite Success",
    topics: ["data", "commercial"],
    type: "press",
    url: "https://www.biopharmadive.com/spons/bridging-the-data-gaps-that-impact-retail-and-specialty-lite-success/747704/",
    buttonLabel: "Read",
  },
  {
    title: "PHIL Invests in State-of-the-Art Cash Dispense Capabilities, Expanding Direct-to-Patient Fulfillment for Pharma",
    topics: ["direct", "access"],
    type: "press",
    url: "https://www.businesswire.com/news/home/20260421670832/en/PHIL-Invests-in-State-of-the-Art-Cash-Dispense-Capabilities-Expanding-Direct-to-Patient-Fulfillment-for-Pharma",
    buttonLabel: "Read",
  },
  {
    title: "Harnessing the Power of Comprehensive Data to Drive GTN",
    topics: ["data", "commercial"],
    type: "press",
    url: "https://www.drugchannels.net/2025/02/from-data-gaps-to-revenue-gains.html",
    buttonLabel: "Read",
  },
  {
    title: "Transforming the Patient Experience with a Strong Direct-to-Consumer Program",
    topics: ["direct", "patient"],
    type: "blog",
    url: "https://phil.us/transforming-the-patient-experience-with-a-strong-direct-to-consumer-program/",
    buttonLabel: "Read",
  },
  {
    title: "Integrating Telemedicine Into Your Pharmaceutical Brand's DTC Strategy",
    topics: ["direct", "patient"],
    type: "blog",
    url: "https://phil.us/integrating-telemedicine-into-your-pharmaceutical-brand-dtc-strategy/",
    buttonLabel: "Read",
  },
  {
    title: "8 Strategies to Decrease Prescription Abandonment and Improve Medication Adherence",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/8-strategies-to-decrease-prescription-abandonment-and-improve-medication/",
    buttonLabel: "Read",
  },
  {
    title: "Phil Secures $60 Million Growth Capital Facility from K2 HealthVentures to Accelerate AI Integration",
    topics: ["data"],
    type: "press",
    url: "https://www.prnewswire.com/news-releases/phil-secures-60-million-growth-capital-facility-from-k2-healthventures-to-accelerate-ai-integration-302499313.html",
    buttonLabel: "Read",
  },
  {
    title: "Is your Patient Access Hub a Strategic Partner?",
    topics: ["access", "patient"],
    type: "blog",
    url: "https://phil.us/is-your-patient-access-hub-a-strategic-partner/",
    buttonLabel: "Read",
  },
  {
    title: "The Case for an Alternative Channel Strategy in Specialty-Lite",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/the-case-for-an-alternative-channel-strategy-in-2024-and-beyond/",
    buttonLabel: "Read",
  },
  {
    title: "How Non-Dispensing Pharmacies can Improve the Patient Access Journey",
    topics: ["access", "patient"],
    type: "blog",
    url: "https://phil.us/how-non-dispensing-pharmacies-can-improve-the-patient-access-journey/",
    buttonLabel: "Read",
  },
  {
    title: "How Can Pharma Manufacturers Improve Patient Engagement in 2025?",
    topics: ["patient"],
    type: "blog",
    url: "https://www.phil.us/how-can-pharma-manufacturers-improve-patient-engagement-in-2025",
    buttonLabel: "Read",
  },
  {
    title: "8 Patient Access Trends Pharma Leaders Should Consider in 2025",
    topics: ["access", "direct"],
    type: "blog",
    url: "https://www.phil.us/8-patient-access-trends-pharma-leaders-should-consider-in-2025",
    buttonLabel: "Read",
  },
  {
    title: "Proactive Steps to Overcoming the Top 3 Patient Access Barriers to Retail and Specialty-Lite Therapies",
    topics: ["access", "patient", "utilization"],
    type: "blog",
    url: "https://phil.us/proactive-steps-to-overcoming-the-top-3-patient-access-barriers-to-retail/",
    buttonLabel: "Read",
  },
  {
    title: "5 Ways PhilRx Meets Patients' Expectations for Digital Healthcare",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/5-ways-philrx-meets-patients-expectations-for-digital-healthcare/",
    buttonLabel: "Read",
  },
  {
    title: "Translating Data into Actionable Insights to Inform your Patient Access Strategy",
    topics: ["data", "access"],
    type: "blog",
    url: "https://phil.us/translating-data-into-actionable-insights-to-inform-your-patient-access/",
    buttonLabel: "Read",
  },
  {
    title: "How Drug Manufacturers Can Evolve their Provider Engagement Model to Drive Brand Performance",
    topics: ["field", "commercial"],
    type: "blog",
    url: "https://phil.us/how-drug-manufacturers-can-evolve-their-provider-engagement-model-to-drive/",
    buttonLabel: "Read",
  },
  {
    title: "The Evolving Role of Retail Pharmacies: What Branded Retail and Specialty-Lite Manufacturers Need to Know",
    topics: ["access"],
    type: "blog",
    url: "https://phil.us/the-evolving-role-of-retail-pharmacies-what-branded-retail-and-specialty/",
    buttonLabel: "Read",
  },
  {
    title: "5 Trends Set to Impact Patient Access to Prescription Therapy in 2024",
    topics: ["access", "patient"],
    type: "blog",
    url: "https://phil.us/5-trends-set-to-impact-patient-access-to-prescription-therapy-in-2024/",
    buttonLabel: "Read",
  },
  {
    title: "Digital Health's Role in Transforming How Healthcare is Delivered",
    topics: ["field", "data"],
    type: "blog",
    url: "https://phil.us/digital-healths-role-in-transforming-how-healthcare-is-delivered/",
    buttonLabel: "Read",
  },
  {
    title: "How Life Sciences Manufacturers can Meet HCP Expectations for Patient Access Support",
    topics: ["field", "patient"],
    type: "blog",
    url: "https://phil.us/how-life-sciences-manufacturers-can-meet-hcp-expectations-for-patient-access/",
    buttonLabel: "Read",
  },
  {
    title: "Enhancing your Patient Access Hub to Drive Brand Success",
    topics: ["access", "patient", "commercial"],
    type: "blog",
    url: "https://phil.us/enhancing-your-patient-access-hub-to-drive-brand-success/",
    buttonLabel: "Read",
  },
  {
    title: "Leveraging Territory Performance Monitoring to Scale Hub Performance",
    topics: ["field", "access", "commercial"],
    type: "blog",
    url: "https://phil.us/leveraging-territory-performance-monitoring-to-scale-hub-performance/",
    buttonLabel: "Read",
  },
  {
    title: "Why Quality Scripts are Crucial to Ensuring Pharmacy Coverage for Your Brand",
    topics: ["access"],
    type: "blog",
    url: "https://phil.us/why-quality-scripts-are-crucial-to-ensuring-pharmacy-coverage-for-your-brand/",
    buttonLabel: "Read",
  },
  {
    title: "Hubs, Digital Pharmacies, and Specialty Pharmacies: What Pharma Access Teams Should Know",
    topics: ["access"],
    type: "blog",
    url: "https://phil.us/hubs-digital-pharmacies-and-specialty-pharmacies-what-pharma-access-teams/",
    buttonLabel: "Read",
  },
  {
    title: "How Biopharma Companies Can Support Patients with High Deductible Health Plans",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/how-biopharma-companies-can-support-patients-with-high-deductible-health/",
    buttonLabel: "Read",
  },
  {
    title: "How Manufacturers Can Improve Speed to Therapy: Overcoming Common Causes of Prescription Delays",
    topics: ["patient", "commercial"],
    type: "blog",
    url: "https://phil.us/how-manufacturers-can-improve-speed-to-therapy-overcoming-common-causes-of/",
    buttonLabel: "Read",
  },
  {
    title: "4 Commercial Practices Shaping the Future of Life Sciences",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/4-commercial-practices-shaping-the-future-of-life-sciences/",
    buttonLabel: "Read",
  },
  {
    title: "Setting the Stage for a Successful, Modern Hub Services Program",
    topics: ["access", "patient"],
    type: "blog",
    url: "https://phil.us/setting-the-stage-for-a-successful-modern-hub-services-program/",
    buttonLabel: "Read",
  },
  {
    title: "The Impact of Time Constrained HCPs on Life Sciences Commercialization and How Manufacturers Should Adapt",
    topics: ["field", "commercial"],
    type: "blog",
    url: "https://phil.us/the-impact-of-time-constrained-hcps-on-life-sciences-commercialization-and/",
    buttonLabel: "Read",
  },
  {
    title: "Conventional Biopharma Commercial Strategies are No Longer Enough",
    topics: ["commercial", "access"],
    type: "blog",
    url: "https://phil.us/conventional-biopharma-commercial-strategies-are-no-longer-enough/",
    buttonLabel: "Read",
  },
  {
    title: "Why Transparency is Critical in the Patient Access Journey",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/why-transparency-is-critical-in-the-patient-access-journey/",
    buttonLabel: "Read",
  },
  {
    title: "How Life Science Brands Can Successfully Navigate Retail Challenges",
    topics: ["access"],
    type: "blog",
    url: "https://phil.us/how-life-science-brands-can-successfully-navigate-retail-challenges/",
    buttonLabel: "Read",
  },
  {
    title: "Is Telemedicine Part of Your Brand's Go-to-Market Strategy? Delivering an End-to-End Digital Experience is Essential",
    topics: ["direct", "data"],
    type: "blog",
    url: "https://phil.us/is-telemedicine-part-of-your-brands-go-to-market-strategy-delivering-an-end/",
    buttonLabel: "Read",
  },
  {
    title: "3 Reasons Why Your Patient Services Program May be Falling Short on Medication Adherence",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/3-reasons-why-your-patient-services-program-may-be-falling-short-on/",
    buttonLabel: "Read",
  },
  {
    title: "4 Strategies to Maximize Enrollment in your Patient Services Program",
    topics: ["patient", "data"],
    type: "blog",
    url: "https://phil.us/4-strategies-to-maximize-enrollment-in-your-patient-services-program/",
    buttonLabel: "Read",
  },
  {
    title: "Implementing an Effective Bridge Program: Laying the Foundation for Covered Dispenses",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/implementing-an-effective-bridge-program-laying-the-foundation-for-covered/",
    buttonLabel: "Read",
  },
  {
    title: "Launching a New Drug in a Category with Generic Alternatives",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/launching-a-new-drug-in-a-category-with-generic-alternatives/",
    buttonLabel: "Read",
  },
  {
    title: "What Makes Phil's Prior Authorization Process Unique?",
    topics: ["utilization"],
    type: "blog",
    url: "https://phil.us/what-makes-phils-prior-authorization-process-unique/",
    buttonLabel: "Read",
  },
  {
    title: "Transforming the Prior Authorization Process: How Feedback Loops can Improve Patient Access to Life Sciences Brands",
    topics: ["utilization", "commercial"],
    type: "blog",
    url: "https://phil.us/transforming-the-prior-authorization-process-how-feedback-loops-can-improve/",
    buttonLabel: "Read",
  },
  {
    title: "Prior Authorizations: What Pharmaceutical Manufacturers Need to Know",
    topics: ["utilization"],
    type: "blog",
    url: "https://phil.us/prior-authorizations-what-pharmaceutical-manufacturers-need-to-know/",
    buttonLabel: "Read",
  },
  {
    title: "Optimizing Life Sciences Field Teams in the Era of Drug Utilization Management",
    topics: ["field", "utilization", "commercial"],
    type: "blog",
    url: "https://phil.us/optimizing-life-sciences-field-teams-in-the-era-of-drug-utilization/",
    buttonLabel: "Read",
  },
  {
    title: "Phil Inc. Adds Duchesnay USA's Women's Healthcare Product to Its Patient Access Platform",
    topics: ["access"],
    type: "press",
    url: "https://www.businesswire.com/news/home/20230109005280/en/Phil-Inc.-Adds-Duchesnay-USAs-Womens-Healthcare-Product-to-Its-Patient-Access-Platform",
    buttonLabel: "Read",
  },
  {
    title: "3 Reasons to Work with a Commercialization Partner that has an Integrated Distribution Network",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/3-reasons-to-work-with-a-commercialization-partner-that-has-an-integrated/",
    buttonLabel: "Read",
  },
  {
    title: "How to Make the Most of your Manufacturer-sponsored Financial Assistance",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/how-to-make-the-most-of-your-manufacturer-sponsored-financial-assistance/",
    buttonLabel: "Read",
  },
  {
    title: "Not Getting Traction with Your Patient Services Program? Here's Why and What to do About it",
    topics: ["patient"],
    type: "blog",
    url: "https://phil.us/not-getting-traction-with-your-patient-services-program-heres-why-and-what/",
    buttonLabel: "Read",
  },
  {
    title: "Why Strong Market Access Doesn't Always Translate to Covered Dispenses",
    topics: ["utilization", "access", "commercial"],
    type: "blog",
    url: "https://phil.us/why-strong-market-access-doesnt-always-translate-to-covered-dispenses/",
    buttonLabel: "Read",
  },
  {
    title: "Tech Enabled Patient Services: Do More With Less in 2023",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/tech-enabled-patient-services-do-more-with-less-in-2023/",
    buttonLabel: "Read",
  },
  {
    title: "8 Metrics that Matter When it Comes to Measuring Your Patient Access Program",
    topics: ["patient", "commercial", "data"],
    type: "blog",
    url: "https://phil.us/8-metrics-that-matter-when-it-comes-to-measuring-your-patient-access-program/",
    buttonLabel: "Read",
  },
  {
    title: "Developing a Distribution Strategy that Optimizes Gross to Net",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/developing-a-distribution-strategy-that-optimizes-gross-to-net/",
    buttonLabel: "Read",
  },
  {
    title: "Are Traditional Hub Providers Keeping Pace with Today's Consumers and Providers?",
    topics: ["access", "data"],
    type: "blog",
    url: "https://phil.us/are-traditional-hub-providers-keeping-pace-with-todays-consumers-and/",
    buttonLabel: "Read",
  },
  {
    title: "Tech Enabled Patient Access Webinar: Key Takeaways",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/tech-enabled-patient-access-webinar-key-takeaways/",
    buttonLabel: "Read",
  },
  {
    title: "How Pharmaceutical Manufacturers can Leverage Phil's Technology to Improve Patient Access to Their Therapies",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/how-pharmaceutical-manufacturers-can-leverage-phils-technology-to-improve/",
    buttonLabel: "Read",
  },
  {
    title: "3 Ways for Pharmaceutical Companies to Improve the Probability of Launch Success",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/three-ways-for-pharmaceutical-companies-to-improve-the-probability-of-launch-success/",
    buttonLabel: "Read",
  },
  {
    title: "Why Your Channel Strategy Matters",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/why-your-channel-strategy-matters/",
    buttonLabel: "Read",
  },
  {
    title: "3 Ways Healthcare Technology is Improving Medication Adherence",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/three-ways-healthcare-technology-is-improving-medication-adherence/",
    buttonLabel: "Read",
  },
  {
    title: "Where's the Data? The Healthcare Data You Need to Drive Commercialization",
    topics: ["data", "commercial"],
    type: "blog",
    url: "https://phil.us/where-is-the-data-the-healthcare-data-you-need-to-drive-commercialization/",
    buttonLabel: "Read",
  },
  {
    title: "How to Streamline Pharmaceutical Commercialization",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/how-to-streamline-pharmaceutical-commercialization/",
    buttonLabel: "Read",
  },
  {
    title: "Optimizing your Drug Distribution Model",
    topics: ["access"],
    type: "blog",
    url: "https://phil.us/optimizing-your-drug-distribution-model/",
    buttonLabel: "Read",
  },
  {
    title: "Determining the Optimal Channel Strategy for Your Pharma Brand",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/optimal-channel-strategy-your-pharma-brand/",
    buttonLabel: "Read",
  },
  {
    title: "Technology Trends Shaping the Future of the Pharmaceutical Commercialization",
    topics: ["data", "commercial"],
    type: "blog",
    url: "https://phil.us/technology-trends-in-pharmaceutical-commercialization/",
    buttonLabel: "Read",
  },
  {
    title: "3 Patient Engagement Technology Myths",
    topics: ["data", "patient"],
    type: "blog",
    url: "https://phil.us/3-patient-engagement-technology-myths/",
    buttonLabel: "Read",
  },
  {
    title: "6 Healthcare Trends Impacting Pharma Commercialization",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/6-trends-impacting-pharma-commercialization/",
    buttonLabel: "Read",
  },
  {
    title: "Is Your Life Science Company Taking Full Advantage of Digital Technology?",
    topics: ["data"],
    type: "blog",
    url: "https://phil.us/life-science-company-digital-technology/",
    buttonLabel: "Read",
  },
  {
    title: "Is Your Pharma Product at Risk for a Mid-Life Cycle Crisis?",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/pharma-product-mid-life-cycle-risk/",
    buttonLabel: "Read",
  },
  {
    title: "Prior Authorization Hurdles Don't Discriminate By Disease",
    topics: ["utilization"],
    type: "blog",
    url: "https://phil.us/prior-authorizations-impacting-therapy-delivery/",
    buttonLabel: "Read",
  },
  {
    title: "How Small Pharma Manufacturers can Optimize Drug Commercialization through Outsourcing",
    topics: ["commercial"],
    type: "blog",
    url: "https://phil.us/small-pharma-manufacturers-drug-commercialization-outsourcing/",
    buttonLabel: "Read",
  },
  {
    title: "Is Your Market Access Strategy Meeting the Needs of Drug Formulary Decision Makers?",
    topics: ["utilization", "commercial"],
    type: "blog",
    url: "https://phil.us/market-access-strategy-drug-formulary/",
    buttonLabel: "Read",
  },
  {
    title: "Does Your Pharmaceutical Brand's Data Demonstrate Value to Payers?",
    topics: ["data", "commercial"],
    type: "blog",
    url: "https://phil.us/does-your-pharmaceutical-brands-data-demonstrate-value-to-payers/",
    buttonLabel: "Read",
  },
  {
    title: "Leveraging Data Analytics to Boost Pharmaceutical Market Access",
    topics: ["data", "commercial"],
    type: "blog",
    url: "https://phil.us/leveraging-data-analytics/",
    buttonLabel: "Read",
  },
  {
    title: "3 Ways a Patient Access Platform Breaks Through Barriers to Medication",
    topics: ["data", "patient", "utilization"],
    type: "blog",
    url: "https://phil.us/3-ways-to-breakthrough-barriers-to-medication/",
    buttonLabel: "Read",
  },
  {
    title: "How to Choose the Best Commercialization Partner to Drive Patient Access",
    topics: ["access", "commercial"],
    type: "blog",
    url: "https://phil.us/how-to-choose-the-best-commercialization-partner-to-drive-patient-access/",
    buttonLabel: "Read",
  },
  {
    title: "On-Demand Webinar: Innovative Strategies to Streamline the Access Journey for Patients & Providers",
    topics: ["access", "patient"],
    type: "webinar",
    url: "https://phil.us/on-demand-webinar-innovative-strategies-to-streamline-the-access-journey-for/",
    buttonLabel: "Watch",
  },
  {
    title: "On-Demand Webinar: Delivering on Direct-to-Consumer: Exceeding Patient Expectations for Virtual Care",
    topics: ["direct", "patient"],
    type: "webinar",
    url: "https://phil.us/on-demand-webinar-delivering-on-direct-to-consumer-exceeding-patient/",
    buttonLabel: "Watch",
  },
  {
    title: "On-Demand Webinar: Optimizing Your Field Team to Maximize Patient Access",
    topics: ["field", "commercial"],
    type: "webinar",
    url: "https://phil.us/optimizing-your-field-team-to-maximize-patient-access-webinar/",
    buttonLabel: "Watch",
  },
  {
    title: "On-Demand Webinar: Improving Patient Access to Medications by Simplifying the Prescription Process",
    topics: ["data", "patient"],
    type: "webinar",
    url: "https://phil.us/webinar-improving-patient-access-to-medications-by-simplifying-the/",
    buttonLabel: "Watch",
  },
  {
    title: "On-Demand Webinar: Tech Enabled Patient Access",
    topics: ["data", "access"],
    type: "webinar",
    url: "https://phil.us/on-demand-webinar-tech-enabled-patient-access/",
    buttonLabel: "Watch",
  },
  {
    title: "Setting the Stage for Commercial Success in 2025 and Beyond",
    topics: ["commercial"],
    type: "report",
    url: "https://phil.us/setting-the-stage-for-commercial-success-in-2025-and-beyond/",
    buttonLabel: "Download",
  },
  {
    title: "Building a Direct-to-Consumer Program that Wins",
    topics: ["direct", "access"],
    type: "report",
    url: "https://phil.us/building-a-direct-to-consumer-program-that-works/",
    buttonLabel: "Download",
  },
  {
    title: "Innovating Your HCP Engagement Model",
    topics: ["field", "data"],
    type: "report",
    url: "https://phil.us/innovating-your-hcp-engagement-model/",
    buttonLabel: "Download",
  },
  {
    title: "Key Success Factors to Drive Brand Excellence",
    topics: ["access", "patient", "utilization"],
    type: "report",
    url: "https://phil.us/key-success-factors-to-drive-brand-excellence/",
    buttonLabel: "Download",
  },
  {
    title: "Designing an Exceptional Life Sciences Hub",
    topics: ["access", "patient"],
    type: "report",
    url: "https://phil.us/life-sciences-hub-design/",
    buttonLabel: "Download",
  },
  {
    title: "Strategies to Ensure the Long-term Success of Your Patient Services Programs",
    topics: ["patient", "commercial"],
    type: "report",
    url: "https://phil.us/5-strategies-to-ensure-the-long-term-success-of-your-patient-services/",
    buttonLabel: "Download",
  },
  {
    title: "Optimizing Patient Access for Sustainable Growth",
    topics: ["access", "commercial"],
    type: "report",
    url: "https://phil.us/optimizing-patient-access-for-sustainable-growth/",
    buttonLabel: "Download",
  },
  {
    title: "Improving Prescription Coverage at the Pharmacy",
    topics: ["access"],
    type: "report",
    url: "https://phil.us/improving-prescription-coverage-at-the-pharmacy/",
    buttonLabel: "Download",
  },
  {
    title: "Improving Adoption of Your Patient Support Services",
    topics: ["patient"],
    type: "report",
    url: "https://phil.us/improving-adoption-of-your-patient-support-services/",
    buttonLabel: "Download",
  },
  {
    title: "Successfully Navigating Prior Authorizations",
    topics: ["utilization"],
    type: "report",
    url: "https://phil.us/successfully-navigating-prior-authorizations/",
    buttonLabel: "Download",
  },
  {
    title: "Modernizing the Patient Access Experience",
    topics: ["patient", "data"],
    type: "report",
    url: "https://phil.us/modernizing-the-patient-access-experience/",
    buttonLabel: "Download",
  },
  {
    title: "Defining Success for Patient Support Services",
    topics: ["patient"],
    type: "report",
    url: "https://phil.us/defining-success-for-patient-support-services/",
    buttonLabel: "Download",
  },
  {
    title: "Driving Adoption in a Crowded Market by Removing Access Barriers",
    topics: ["patient", "access", "data", "commercial"],
    type: "casestudy",
    url: "https://phil.us/insights/case-studies/philrx-launches-robust-channel-strategy-for-specialty-lite-migraine-brand/",
    buttonLabel: "Read",
  },
  {
    title: "Overcoming Low Enrollment and High Abandonment Rates",
    topics: ["patient", "access", "data", "commercial"],
    type: "casestudy",
    url: "https://phil.us/insights/case-studies/philrx-unlocks-90-dispense-coverage-for-womens-health-brand/",
    buttonLabel: "Read",
  },
  {
    title: "Addressing Two Critical Issues: Prescriber Adoption & Patient Adherence",
    topics: ["patient", "access", "data", "commercial"],
    type: "casestudy",
    url: "https://phil.us/insights/case-studies/philrx-drives-high-adoption-for-ophthalmology-brand/",
    buttonLabel: "Read",
  },
  {
    title: "Designing a Transformative Direct-to-Patient Program to Drive Brand Growth",
    topics: ["direct", "patient", "access", "data", "commercial"],
    type: "casestudy",
    url: "https://phil.us/insights/case-studies/philrx-designs-transformative-telemedicine-channel-for-womens-health-brand/",
    buttonLabel: "Read",
  },
];
