# .github/workflows/ci.yml
name: CI
# Run this workflow on any push to any branch.
on: [push, pull_request]

# Set environment variables
env:
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  SPACE_ID: ${{ secrets.SPACE_ID }}

# A workflow can have one or more jobs.
jobs:
  # This workflow has just a single job named `ci`.
  ci:
    # Run this job on a Github hosted action runner with the latest version of ubuntu installed.
    runs-on: ubuntu-latest
    # A job has one or more steps.
    steps:
      # Checkout the project source files to the Github Action runner.
      # This is roughly equivalent to running `git checkout`.
      - name: Checkout source
        uses: actions/checkout@v3
      # Install the version of Node.js used by project.
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.17.1"
      # Install package dependencies as defined in package.json file in root of project.
      - name: install
        run: yarn install
      # Run `gatsby build`.
      - name: build
        run: yarn build
